print("Welcome to the project Marlboro Township Recreational Basketball Lineups Generator!")
print("Please answer the following questions to generate the strongest lineups possible for your team.")
print('                                                ')

# Ask for the number of players
num_players = int(input("Does your team have 8 or 9 players? Please enter 8 or 9: "))
print('                                                ')

# Common inputs for both cases
player_1 = input("Who's your best player? ")
print('                                                ')
player_2 = input("Who's your second best player? ")
print('                                                ')
player_3 = input("Who's your third best player? ")
print('                                                ')
player_4 = input("Who's your fourth best player? ")
print('                                                ')
player_5 = input("Who's your fifth best player? ")
print('                                                ')
player_6 = input("Who's your sixth best player? ")
print('                                                ')
player_7 = input("Who's your seventh best player? ")
print('                                                ')
player_8 = input("Who's your eighth best player? ")

# If the team has 9 players, ask for the ninth player
if num_players == 9:
    print('                                                ')
    player_9 = input("Who's your ninth best player? ")

print('________________________________________________')
print('                                                ')
print("Strongest and Most Balanced Lineups for Your Team:")
print('________________________________________________')
print('                                                ')

# Generate lineups based on the number of players
if num_players == 9:
    print("Segment 1: ")
    print(player_1, player_2, player_6, player_8, player_9)
    print('                                                ')
    print("Segment 2: ")
    print(player_2, player_3, player_4, player_7, player_8)
    print('                                                ')
    print("Segment 3: ")
    print(player_1, player_3, player_5, player_6, player_9)
    print('                                                ')
    print("Segment 4: ")
    print(player_2, player_3, player_5, player_7, player_9)
    print('                                                ')
    print("Segment 5: ")
    print(player_1, player_4, player_6, player_7, player_8)
    print('                                                ')
    print("Segment 6: ")
    print(player_1, player_2, player_3, player_4, player_5)
    print('                                                ')
else:
    print("Segment 1: ")
    print(player_1, player_2, player_4, player_6, player_8)
    print('                                                ')
    print("Segment 2: ")
    print(player_2, player_3, player_4, player_5, player_7)
    print('                                                ')
    print("Segment 3: ")
    print(player_1, player_3, player_5, player_6, player_8)
    print('                                                ')
    print("Segment 4: ")
    print(player_2, player_3, player_5, player_6, player_7)
    print('                                                ')
    print("Segment 5: ")
    print(player_1, player_4, player_6, player_7, player_8)
    print('                                                ')
    print("Segment 6: ")
    print(player_1, player_2, player_3, player_4, player_5)
    print('                                                ')

print('________________________________________________')
print("This is the strongest and most balanced lineup detected for your team data.")
print("Feel free to make any changes to your lineup or information. Thank you for using")
print("Lineups Generator, and we wish you the best of luck for your next game!")
print('                                                ')
print("More coming soon (7 player lineups plus digital game coach!) ")
